<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Panel de Control</title>
</head>

<body>
    <div class="container">
        <a href="index.php" width="25"><img src="logo.ico" class="bg-primary" alt="" width=25 /></a>
        <div class="bg-primary text-white text-center py-3 mb-3">
            <h1>Panel de control</h1>
        </div>
        <div class="col-md-3">
            <button class="btn btn-primary mb-3" id="publicar" onclick="location.href='index.php?c=article&nuevo=1'">Publicar nuevo artículo</button>
            <button class="btn btn-primary mb-3" id="cambiarRol" onclick="location.href='index.php?c=admin&cambiarRoles=1'">Cambiar rol a usuarios</button>

        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>

</html>