<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=ç, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form action="index.php" method="POST" style="text-align: center;">
        <div>
            <fieldset style="display: inline-block;">
                <input type="text" name="user" placeholder="Nombre de usuario" required /><br>
                <input type="password" name="password" placeholder="Contraseña" required /><br>&nbsp;<br>
                <input type="submit" name="login" value="Entrar" /><br>
            </fieldset>
        </div>
        <a href="index.php?invitado=1">invitado</a>&nbsp;<a href="index.php?registro=1">registrarse</a>
    </form>
</body>
</html>