<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Blog</title>
</head>

<body>
    <div class="container">
        <div class="bg-primary text-white md-3 d-flex align-items-center">
        <a href="index.php"><img src="logo.ico" alt="" width=50/></a> <h1 style="display:inline">Blog</h1>
        </div>
    <?php
    if (isset($_GET['registro'])) {
    ?>
        <form action="index.php?c=user" method="POST" style="text-align: center;">
            <div>
                <fieldset style="display: inline-block;">
                    <input type="text" class="form-control my-2" name="nombre" placeholder="Nuevo nombre de usuario" required /><br>
                    <input type="text" class="form-control my-2" name="password" placeholder="Elija una contraseña" required /><br>&nbsp;<br>
                    <input type="submit" class="form-control bg-primary text-white" name="register" value="Registrarse" /><br>
                </fieldset style="display: inline-block;">
            </div>
            <a href="index.php?c=user">login</a>
        </form>
    <?php
    }



    if (isset($_GET['comentar']) && $_SESSION['user']->getRol() > 0) {
    ?>
        <form action="index.php?c=comment" method="POST" class="form-control">
            <div>
                <fieldset style="display: inline-block;">
                    <textarea name="text" cols="40" rows="5" placeholder="Su comentario"></textarea><br>
                    <input type="hidden" id="idArticle" name="idArticle" value="<?php echo $_GET['comentar']; ?>" />
                    <input type="hidden" id="subcomentario" name="subcomentario" value="<?php echo $_GET['subC']; ?>" />
                    <input type="submit" id="comment" name="comment" value="Comentar" />
                    <button class="btn" onclick="href.location='index.php'">Cancelar</button><br>
                </fieldset>
            </div>
        </form>
    <?php
    }

    if (isset($_GET['modificar']) && $_SESSION['user']->getRol() > 0) {
        $com = CommentRepository::getCommentById($_GET['modificar']);
        $text = $com->getText();
    ?>
        <form action="index.php?c=comment" method="POST">
            <div>
                <fieldset style="display: inline-block;">
                    <textarea name="text" cols="40" rows="5"><?php echo $text; ?></textarea><br>
                    <input type="hidden" id="idComment" name="idComment" value="<?php echo $com->getId(); ?>">
                    <input type="submit" name="modify" value="Actualizar" /><br>
                </fieldset>
            </div>
        </form>
        <?php
    }

    if (isset($_SESSION['user'])) {
        ?>
        <form action="index.php?c=article" method=POST>
            <input type="search" name="query"/>
            <input type="submit" value="Buscar"/>
        </form>
        <?php

        echo "<p> Usuario: " . $_SESSION['user']->getName();
        echo " - Rol: " . $_SESSION['user']->getRol() . "</p><br>";
        if ($_SESSION['user']->getRol() > 1) echo "<a href='index.php?c=admin&panelDeControl=1'>Panel de Control</a><br>";
        echo "<a href='index.php?logout=1&c=user'>logout</a>";


        echo "<table><tr><th>Id</th><th>Título</th><th>Texto</th><th>Fecha</th><th>Autor</th><th></th></tr>";

        foreach ($articulos as $articulo) {
            echo '<tr><td>' . $articulo->getId() . '</td><td>'
                . $articulo->getTitle() . '</td><td style="font-size:1.2em;background-color:lightgray;">'
                . $articulo->getText() . '</td><td>'
                . $articulo->getDate() . '</td><td>'
                . $articulo->getAuthor()->getName() . "</td><td>"
                . (($_SESSION['user']->getRol() > 0) ? "<a href='index.php?c=user&comentar=" . $articulo->getId() . "&subC=0'>comentar</a>" : '') . "</td><tr>";
                foreach($articulo->getComments() as $comment){
                    if ($comment->getIdComment() == 0) {
                        CommentRepository::imprimeComentarios($articulo->getId(), [$comment]);
                    }
                }
        }
        echo "</table>";

    } else {
        if (!isset($_GET['registro'])) {
        ?>
            <form action="index.php?c=user" method="POST" style="text-align: center;">
                <div>
                    <fieldset style="display: inline-block;">
                        <input type="text" name="user" placeholder="Nombre de usuario" required /><br>
                        <input type="password" name="password" placeholder="Contraseña" required /><br>&nbsp;<br>
                        <input type="submit" name="login" value="Entrar" /><br>
                    </fieldset>
                </div>
                <a href="index.php?invitado=1&c=user">invitado</a>&nbsp;<a href="index.php?registro=1&c=user">registrarse</a>
            </form>
    <?php

        }
    }
    ?>

    </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>