<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Crear nuevo artículo</title>
</head>

<body>
    <div class="container">
        <a href="index.php" width="25"><img src="logo.ico" class="bg-primary" alt="" width=25 /></a>
        <div class="bg-primary text-white text-center py-3 mb-3">
            <h1>Nuevo Artículo</h1>
        </div>
        <div class="row">
            <form action="index.php?c=article" method="POST">
                <div>
                    <fieldset style="display: inline-block;">
                        <input type="text" name="title" placeholder="Título del artículo" /><br>
                        <textarea name="text" cols="40" rows="5" placeholder="Su artículo"></textarea><br>
                        <input type="hidden" name="idUser" <?php echo 'value="'.$_SESSION['user']->getId().'"'; ?>>
                        <input type="submit" name="newArticle" value="Publicar" /><br>
                    </fieldset>
                </div>
            </form>            
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>