<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
</head>
<body>
<form action="index.php" method="POST" style="text-align: center;">
    <div><fieldset style="display: inline-block;">
        <input type="text" name="nombre" placeholder="Nuevo nombre de usuario" required /><br>
        <input type="text" name="password" placeholder="Elija una contraseña" required /><br>&nbsp;<br>
        <input type="submit" name="register" value="Registrarse" /><br>
    </fieldset style="display: inline-block;"></div>
    <a href="index.php?logout=1">login</a>
</form>
</body>
</html>